version: "3.3"

services:
  rs_b:
    image: artinbitslab/rs_b:1.1
    container_name: rs_b
    volumes:
      - /dev:/dev
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /opt/rotem_sela_top/backend-docker/rotem_sela_backend:/opt/rotem_sela
      - ./entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh
    network_mode: host
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  rs_f:
    image: artinbitslab/rs_f:latest
    container_name: rs_f
    network_mode: host
